apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
stringData:
  username: postgres
  password: postgres
  url: host=postgres user=postgres password=postgres dbname=caloriedb port=5432 sslmode=disable
